# Generated by Django 4.0 on 2022-01-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_keyvalue_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_vars', to='api.app'),
        ),
    ]
