# Generated by Django 4.0 on 2022-01-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_container'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyValue',
            new_name='EnvVar',
        ),
    ]
