# Generated by Django 4.0 on 2022-01-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_keyvalue_envvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='command',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
